#!/usr/bin/env python3
"""
Render docs/content-audit.md from docs/reading-library-map.json.

The map is the authoritative, machine-readable record of what the audit
decided about each source document; this is its human-readable view. Keeping
the prose generated means the two can never disagree, which matters because
PROJECT_STATUS.md points a resuming session at both.

Usage:
    python3 scripts/build_content_audit.py
"""
import collections
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MAP = REPO_ROOT / "docs" / "reading-library-map.json"
OUT = REPO_ROOT / "docs" / "content-audit.md"

ORDER = ["DELETE", "REPLACE", "MERGE", "SPLIT", "EDIT", "CONVERT", "KEEP"]
BLURB = {
    "DELETE": "Nothing worth migrating. Each reason is given -- no existing material is dropped silently.",
    "REPLACE": "The slot is worth keeping, but authoring a new text beats repairing this one.",
    "MERGE": "Two or more files teach essentially the same language in essentially the same context.",
    "SPLIT": "Several unrelated materials share one file; each deserves its own page, exercises and audio.",
    "EDIT": "Useful material that needs correction before it goes on the site.",
    "CONVERT": "Not a reading text -- a drill, answer key or discussion bank. Becomes an HTML exercise component (audio not applicable).",
    "KEEP": "Already good; convert as-is.",
}
AUDIO_NOTES = [
    ("required", "must be generated"),
    ("exists", "mp3 present and matches the text"),
    ("stale-on-edit", "mp3 present but the text is being edited -- **must be regenerated**"),
    ("n/a", "drill / answer key / discussion bank -- not a reading text"),
]


def main():
    T = json.loads(MAP.read_text(encoding="utf-8"))["texts"]
    L = []
    w = L.append
    w("# Content audit — reading & exercise library\n")
    w("Generated by `scripts/build_content_audit.py` from `docs/reading-library-map.json`, which is")
    w("the authoritative machine-readable map. Every one of the **%d source documents** in" % len(T))
    w("`cefr/texts/` was extracted and read in full before being classified here; nothing in this")
    w("table was inferred from a filename.\n")
    w("Extraction used the `.docx` wherever one exists (the `.pdf` is an export of the same document).\n")
    w("See `PROJECT_STATUS.md` for the target architecture, the editorial rules and the next actions.\n")

    done = sum(1 for t in T if t.get("status") == "IMPLEMENTED")
    w(f"**Progress: {done} of {len(T)} implemented.**\n")

    w("## Totals\n")
    w("| Action | Count | Meaning |")
    w("|---|---:|---|")
    for a in ORDER:
        w(f"| {a} | {sum(1 for t in T if t['action'] == a)} | {BLURB[a].split('.')[0]}. |")
    w(f"| **Total** | **{len(T)}** | |\n")

    w("### Recommended level\n")
    w("| Level | Docs |")
    w("|---|---:|")
    for lv in ["A1", "A2", "B1", "B2", "C1", "C2", "n/a"]:
        w(f"| {lv} | {sum(1 for t in T if t['level'] == lv)} |")
    w("\n**A1 has 1 document and C2 has none.** The library's centre of gravity is B1. A coherent")
    w("A1-to-C2 progression therefore needs newly authored A1 material and a small, genuinely")
    w("justified C2 set -- flagged as P-1 in `PROJECT_STATUS.md`, and to be labelled as new")
    w("content rather than as pre-existing.\n")

    w("### Audio requirement\n")
    w("| Audio | Docs | |")
    w("|---|---:|---|")
    for k, note in AUDIO_NOTES:
        w(f"| `{k}` | {sum(1 for t in T if t['audio'] == k)} | {note} |")
    w("\n---\n")

    for a in ORDER:
        rows = sorted((t for t in T if t["action"] == a), key=lambda t: t["slug"])
        w(f"## {a} ({len(rows)})\n")
        w(BLURB[a] + "\n")
        w("| Source | Words | Genre | Level | Topic | Audio | Status | Reason |")
        w("|---|---:|---|---|---|---|---|---|")
        for t in rows:
            src = t.get("source_slug", t["slug"])
            tgt = f"<br>→ `{t['merge_into']}`" if t.get("merge_into") else ""
            page = f"<br>[page]({'../' + t['page']})" if t.get("page") else ""
            w(f"| `{src}`{tgt}{page} | {t['words'] or '—'} | {t['genre']} | {t['level']} | "
              f"{t['topic']} | `{t['audio']}` | {t.get('status', '—')} | {t['reason']} |")
        w("")

    w("---\n")
    w("## Merge targets\n")
    m = collections.defaultdict(list)
    for t in T:
        if t.get("merge_into"):
            m[t["merge_into"]].append(t.get("source_slug", t["slug"]))
    w(f"The {sum(len(v) for v in m.values())} MERGE entries collapse into these {len(m)} pages:\n")
    w("| Merge target | Sources |")
    w("|---|---|")
    for k in sorted(m):
        w(f"| `{k}` | {', '.join('`' + s + '`' for s in sorted(m[k]))} |")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)} ({len(L)} lines, {done}/{len(T)} implemented)")


if __name__ == "__main__":
    main()
